### ISSUE TITLE
v1.2.0 path splitting issue

### ISSUE THREAD

**Issue by matthiasotto** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#100]
Hi all,
with 1.2.0 we noticed ExtractPO breaking for us (on CI and locally). Downgrading to 1.1.0 resolved the issue. 

It is failing on this line: https://github.com/OrchardCoreContrib/OrchardCoreContrib.PoExtractor/compare/v1.1.0...v1.2.0#diff-278f797f65a94d95062662ff3b79e00916d305d4bf7e41cfbb13224c9d4d2373R87

**CI Job output:**
```
Tool 'orchardcorecontrib.poextractor' (version '1.2.0') was successfully installed.

> extractpo C:\git\appName\WebApps\AppName\ProjectFolder C:\git\appName\outputFolder --language "C#" --template "razor"

Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex, Int32 length)
   at OrchardCoreContrib.PoExtractor.Program.Main(String[] args) in G:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor\Program.cs:line 87
```

Thank you for your help,
Matthias

**Comment by hishamco** [comment]
Hi Matthias, please steps to reproduce

**Comment by hishamco** [comment]
I tried to use the same command from within the code-base there's no error shows up

**Comment by hishamco** [comment]
FYI https://github.com/OrchardCMS/OrchardCore/pull/17039#issuecomment-2489614914

**Comment by hishamco** [comment]
@matthiasotto do you still facing the issue or shall I close this issue?
