### ISSUE TITLE
Unhandled exception when using Raw String Literal

### ISSUE THREAD

**Issue by BrunoJuchli** [OrchardCoreContrib/OrchardCoreContrib.PoExtractor#85]
Hi There

Let me start by saying: Thank you for this tool!

------

## Repro Case

```C#
S[
    """
    The current configuration is in an invalid state and cannot be restored. 
    It may be that a load management group or a meter has been deleted. 
    The configuration will be deleted now.
    """
 ];
```

when replacing the above with:
```C#
S["foo"];
```

The error vanishes.
A multiline verbatim (`@"..."`) string also works (but doesn't produce the same result, so isn't a viable alternative).

## Exception

> Unhandled exception. System.ArgumentException: 'text' cannot be null or empty. (Parameter 'text')
   at OrchardCoreContrib.PoExtractor.LocalizableStringExtractor`1.CreateLocalizedString(String text, String textPlural, TNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.Abstractions\LocalizableStringExtractor.cs:line 35
   at OrchardCoreContrib.PoExtractor.DotNet.CS.SingularStringExtractor.TryExtract(SyntaxNode node, LocalizableStringOccurence& result) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet.CS\SingularStringExtractor.cs:line 44
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 36
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at Microsoft.CodeAnalysis.SyntaxWalker.Visit(SyntaxNode node)
   at OrchardCoreContrib.PoExtractor.DotNet.ExtractingCodeWalker.Visit(SyntaxNode node) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet\ExtractingCodeWalker.cs:line 34
   at OrchardCoreContrib.PoExtractor.DotNet.CS.CSharpProjectProcessor.Process(String path, String basePath, LocalizableStringCollection localizableStrings) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor.DotNet.CS\CSharpProjectProcessor.cs:line 60
   at OrchardCoreContrib.PoExtractor.Program.Main(String[] args) in D:\Repositories\OrchardCoreContrib.PoExtractor\src\OrchardCoreContrib.PoExtractor\Program.cs:line 100

## PR / Fix
If you agree that this should be a supported use case, I can look into creating a PR - if you want me to.

### Off-topic
We're looking into using this tool outside of Orchard. I think it's very useful to have PO files extracted from source code. This way we can skip creating .resx files by hand, can easily automate synchronization and have added plural support 👍 If it were up to me this should become the new standard in .net land 🥇:-) So thank you for creating this useful tool.
 
Do you know of any other tools in the .net landscape that offers basically the same as this?
I know that [Soluling](https://www.soluling.com/Help/Blazor/Index.htm) offers something similar, but they generate a .resx file.

**Comment by BrunoJuchli** [comment]
> > Let me start by saying: Thank you for this tool!
> 
> You could thank @lukaskabrt who is the original author :)

Well then, thank you @lukaskabrt !

> > A multiline verbatim (@"...") string also works (but doesn't produce the same result, so isn't a viable alternative).
> 
> @sebastienros I think we already support multiline resources, right?

I guess I was expressing myself in a confusing way :-) Yes, the multi-line verbatim string works. It's just that the multiline verbatim string doesn't work. I've added some insights into what the parsed syntax tree looks like.

**Comment by hishamco** [comment]
I see, modify your PR with the required change, I'm so close to publishing `1.1.0` release

**Comment by hishamco** [comment]
> We're looking into using this tool outside of Orchard. I think it's very useful to have PO files extracted from source code

@BrunoJuchli what limitations are you facing? I remember the `S`, `T` could be customized for non OC apps

**Comment by BrunoJuchli** [comment]
> I see, modify your PR with the required change, I'm so close to publishing `1.1.0` release

Thanks, I'll have a look 👍

**Comment by BrunoJuchli** [comment]
> > We're looking into using this tool outside of Orchard. I think it's very useful to have PO files extracted from source code
> 
> @BrunoJuchli what limitations are you facing? I remember the `S`, `T` could be customized for non OC apps

Maybe you might want to enable/allow discussions on this repo, because it might be a better place to discuss this? :-)
Also, I'm not done trying it out and we're not using it "in production" yet, so I can't give definitive feedback, yet.
Anyway, here's some preliminary findings - note that I haven't stumbled upon any big things or even showstoppers, yet:

## Naming Convention

### Violates our project specific Naming Convention

The `S` / `H` / `T` violate our naming convention for fields, because it's upper case. That's a bit of a nuisance, because I have to suppress these violations:
```C#
// ReSharper disable once InconsistentNaming required by PoExtractor
readonly IStringLocalizer S;
```

So I'd be happy if it would support lower-case `s` / `h` / `t`, too (both, because we want uppercase when using property injection (in blazor)).
Actually, I'm not sure it doesn't already support it, haven't tested it...

### Mistakes are silently ignored
If some guy uses a name other than `S`/`H`/`T` then the PO entry will be missing - and there's no error.
So it's a bit dangerous, because it's easy to get wrong, and you'll only notice once users / testers report an unlocalized text.

It's not really important because the impact of an error is quite limited, but it's a pitfall.

## Unstable PO Files
Since the source-code line where the string was extracted is part of the comment, most modifications to the code trigger changes in the PO file, even though the localization themselves haven't changed.
So, adding or removing a using directive changes every entry belonging to that source code file.
That makes the git history grow, leads to additional review work, making working with the history of the PO file harder, and probably - over time - also contributes to worsening git performance.

Also not a huge thing, but maybe it would a good idea to remove the line number from the comment - maybe also make this configurable.

## Shareable Config
Really low prio: It would be nice to be able to specify the config in a config file instead via cmd line arguments.
That would be handy when you call it locally and in your github action, for example.

Low prio because it's not so hard to add a batch/powershell/... file to the repo and just execute this from everywhere...

**Comment by hishamco** [comment]
Feel free to add yours, regarding the tests we usually use Moq. In case you face difficulties use `Verify.Tests` then I can rewrite them using `Moq`

**Comment by hishamco** [comment]
No problem

**Comment by hishamco** [comment]
Is it something like Shouldly?

**Comment by hishamco** [comment]
> Unfortunately I don't think I'll be making any progress on my PR, at least not currently. I'm spiking integrating the PO files in our Blazor WASM Project 

How can I help you with this, AFAIK the PO Extractor doesn't rely on MVC, I knew it uses Razor as one option for the templates but also could use Fluid for Liquid templates

**Comment by BrunoJuchli** [comment]
> How can I help you with this, AFAIK the PO Extractor doesn't rely on MVC, I knew it uses Razor as one option for the templates but also could use Fluid for Liquid templates

Thank you, very nice of you to offer!

The biggest problem is #88

The rest is a problem with [https://www.nuget.org/packages/OrchardCore.Localization](OrchardCore.Localization] and -`.Abstractions`. It would require splitting it both up into 2 packages each: one with the stuff only relying on `StringLocalizer<T>`, and the other with MVC specific stuff (`IViewLocalizer`, `IHtmlAnalyzer`). Maybe even a completely different project split would be better. But this is "just" so that it could be used in a non-orchard context. Or Orchard-Blazor-WASM, if there's going to be something like that ;-)
So I'm not sure this is something the Orchard project would consider, since it already has a ton of projects in the solution...

**Comment by BrunoJuchli** [comment]
This issue is fixed when using the version from `develop`, at least when I run it locally from my IDE. It correctly generates:

```
msgid "Blabla line 1\r\nFoofoo line 2\r\nAnd a third line, maybe?"
```
